In [1]:
import numpy as np

In [7]:
##creating arrays using numpy
##creating a 1 d array
arr_1 = np.array([1,2,3,4,5])
print(f'The array : {arr_1}')
print(f'shape of the array : {arr_1.shape}')
print(f'Type of that array : {type(arr_1)}')
print(f'Reshaping the array to 1,5 : {arr_1.reshape(1,5)}')
print(f'Reshaping the array to 5,1 : {arr_1.reshape(5,1)}')

The array : [1 2 3 4 5]
shape of the array : (5,)
Type of that array : <class 'numpy.ndarray'>
Reshaping the array to 1,5 : [[1 2 3 4 5]]
Reshaping the array to 5,1 : [[1]
 [2]
 [3]
 [4]
 [5]]


In [11]:
arr_2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])
print(f'The array : {arr_2}')
print(f'shape of the array : {arr_2.shape}')
print(f'Type of that array : {type(arr_2)}')


The array : [[1 2 3 4 5]
 [1 2 3 4 5]]
shape of the array : (2, 5)
Type of that array : <class 'numpy.ndarray'>


In [14]:
#Linearly seperable arrays
arr_3 = np.arange(0, 10, 2).reshape(5,1)
arr_3

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
ones_arr = np.ones((3,4))
ones_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
identity_arr = np.eye(3,3)
identity_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
## Numpy vectorized operations

arr_4 = np.array([1,2,3,4,5])
arr_5 = np.array([5,6,7,8,9])

## Element wise addition  these are performed elemt wise
print(f'Addition : {arr_4+arr_5}')
print(f'Subtraction : {arr_4-arr_5}')

Addition : [ 6  8 10 12 14]
Subtraction : [-4 -4 -4 -4 -4]


In [27]:
## Universal Functions
arr = np.array([2,3,4,5,6])
print(f"SQRT : {np.sqrt(arr)}")
print(f'Exponential : {np.exp(arr)}')
print(f'log : {np.log(arr)}')

SQRT : [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential : [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
log : [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [31]:
## Array slicing and indexing

arr1 = np.arange(0,9,1).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
#Statistical Concepts -- Normalization
## to have a mean and std

data = np.arange(0,5,1)

#calculate mean and STD
mean = np.mean(data)
std_dev = np.std(data)

#NOrmalized the data
normalizing_data = (data-mean)/std_dev
print(f'Normalized Data : {normalizing_data}')

Normalized Data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [38]:
## Logical operations
data = np.arange(1,11)
data[(data>5) & (data<8)]  #use logical and for these problems

array([6, 7])